package com.mirkamolcode.model;

public enum Permission {
    SUBSCRIPTION_CREATE,
    SUBSCRIPTION_READ_OWN,
    SUBSCRIPTION_READ_ALL,
    SUBSCRIPTION_UPDATE_OWN,
    SUBSCRIPTION_UPDATE_ALL,
    SUBSCRIPTION_DELETE_OWN,
    SUBSCRIPTION_DELETE_ALL,
    STATISTICS_READ_OWN,
    STATISTICS_READ_ALL
}
