CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(254) NOT NULL,
    password_hash VARCHAR(60) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_users_email UNIQUE (email)
);
CREATE TABLE user_roles (
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role VARCHAR(16) NOT NULL CHECK (role IN ('USER','ADMIN')),
    PRIMARY KEY (user_id, role)
);
CREATE TABLE subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    name VARCHAR(120) NOT NULL,
    price NUMERIC(19,4) NOT NULL CHECK (price > 0),
    currency VARCHAR(3) NOT NULL CHECK (currency IN ('UZS','USD','EUR')),
    frequency VARCHAR(16) NOT NULL CHECK (frequency IN ('WEEKLY','MONTHLY','ANNUAL')),
    status VARCHAR(16) NOT NULL CHECK (status IN ('ACTIVE','PAUSED','CANCELLED')),
    category VARCHAR(20) NOT NULL CHECK (category IN ('ENTERTAINMENT','PRODUCTIVITY','AI_TOOLS','EDUCATION','HEALTH','FINANCE','OTHER')),
    start_date DATE NOT NULL,
    next_payment_date DATE NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_subscription_user_deleted ON subscriptions(user_id, is_deleted);
CREATE INDEX idx_subscription_due ON subscriptions(next_payment_date);
CREATE TABLE exchange_rates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    currency VARCHAR(3) NOT NULL CHECK (currency IN ('USD','EUR')),
    rate_to_uzs NUMERIC(19,6) NOT NULL CHECK (rate_to_uzs > 0),
    rate_date DATE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_exchange_rate_currency_date UNIQUE(currency, rate_date)
);
CREATE TABLE payment_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscription_id BIGINT NOT NULL REFERENCES subscriptions(id),
    payment_date DATE NOT NULL,
    original_amount NUMERIC(19,4) NOT NULL CHECK (original_amount > 0),
    original_currency VARCHAR(3) NOT NULL CHECK (original_currency IN ('UZS','USD','EUR')),
    exchange_rate_to_uzs NUMERIC(19,6) NOT NULL CHECK (exchange_rate_to_uzs > 0),
    amount_uzs NUMERIC(19,4) NOT NULL CHECK (amount_uzs > 0),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_payment_history_subscription ON payment_history(subscription_id);
CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_refresh_token_hash UNIQUE(token_hash)
);
CREATE INDEX idx_refresh_token_hash ON refresh_tokens(token_hash);
CREATE TABLE shedlock (name VARCHAR(64) NOT NULL PRIMARY KEY, lock_until TIMESTAMP NOT NULL, locked_at TIMESTAMP NOT NULL, locked_by VARCHAR(255) NOT NULL);
